'use client';

import { useState } from 'react';
import { runSuiteQL } from '../lib/sqlite.js';

export default function Console() {
  const [question, setQuestion] = useState('');
  const [sql, setSql] = useState('');
  const [explanation, setExplanation] = useState('');
  const [source, setSource] = useState(null);
  const [results, setResults] = useState(null);
  const [error, setError] = useState(null);
  const [busy, setBusy] = useState(false);

  async function generate() {
    if (!question.trim() || busy) return;
    setBusy(true);
    setError(null);
    setResults(null);
    try {
      const res = await fetch('/api/generate', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ question }),
      });
      const data = await res.json();
      if (!res.ok) throw new Error(data.error || 'Generation failed');
      setSql(data.sql);
      setExplanation(data.explanation);
      setSource(data.source);
      await run(data.sql);
    } catch (err) {
      setError(err.message);
    } finally {
      setBusy(false);
    }
  }

  async function run(query = sql) {
    setError(null);
    try {
      const res = await runSuiteQL(query);
      setResults(res);
    } catch (err) {
      setResults(null);
      setError(`Query failed: ${err.message}`);
    }
  }

  return (
    <div className="shell">
      <header className="topbar">
        <div className="brand">
          <span className="brand-mark">◆</span> SuiteSense
          <span className="brand-sub">AI SuiteQL Console</span>
        </div>
        <div className="topbar-right">
          <span className="badge">Demo dataset — runs in your browser</span>
          <a href="https://github.com/tricksterbivek/suitesense" target="_blank" rel="noreferrer">
            GitHub
          </a>
        </div>
      </header>

      <main className="console">
        <section className="ask">
          <label htmlFor="q">Ask a question about your NetSuite data</label>
          <div className="ask-row">
            <textarea
              id="q"
              rows={2}
              placeholder="e.g. Top 10 customers by revenue this year"
              value={question}
              onChange={(e) => setQuestion(e.target.value)}
              onKeyDown={(e) => {
                if (e.key === 'Enter' && !e.shiftKey) {
                  e.preventDefault();
                  generate();
                }
              }}
            />
            <button className="primary" onClick={generate} disabled={busy || !question.trim()}>
              {busy ? 'Generating…' : 'Generate SuiteQL'}
            </button>
          </div>
        </section>

        {sql && (
          <section className="panel">
            <div className="panel-head">
              <h2>SuiteQL</h2>
              <div className="panel-meta">
                {source === 'ai' ? 'Generated by Claude' : source === 'examples' ? 'Curated example (demo mode)' : ''}
              </div>
              <button onClick={() => run()}>Run ▸</button>
            </div>
            <textarea
              className="sql-editor"
              rows={Math.min(14, sql.split('\n').length + 1)}
              value={sql}
              onChange={(e) => setSql(e.target.value)}
              spellCheck={false}
            />
            {explanation && <p className="explanation">{explanation}</p>}
          </section>
        )}

        {error && <div className="error">{error}</div>}

        {results && <ResultsPanel results={results} />}
      </main>
    </div>
  );
}

// Chartable when there are 2-3 columns, the first is a label and the last is numeric.
function isChartable(columns, rows) {
  return (
    columns.length >= 2 &&
    columns.length <= 3 &&
    rows.length >= 2 &&
    rows.length <= 40 &&
    rows.every((r) => typeof r[r.length - 1] === 'number')
  );
}

function ResultsPanel({ results }) {
  const { columns, rows } = results;
  const chartable = isChartable(columns, rows);
  const [view, setView] = useState('table');
  const activeView = chartable ? view : 'table';

  return (
    <section className="panel">
      <div className="panel-head">
        <h2>Results</h2>
        <div className="panel-meta">{rows.length} rows</div>
        {chartable && (
          <div className="view-toggle">
            <button className={activeView === 'table' ? 'active' : ''} onClick={() => setView('table')}>
              Table
            </button>
            <button className={activeView === 'chart' ? 'active' : ''} onClick={() => setView('chart')}>
              Chart
            </button>
          </div>
        )}
      </div>
      {activeView === 'chart' ? <BarChart columns={columns} rows={rows} /> : <ResultsTable columns={columns} rows={rows} />}
    </section>
  );
}

function BarChart({ columns, rows }) {
  const valueIndex = rows[0].length - 1;
  const max = Math.max(...rows.map((r) => Math.abs(r[valueIndex])), 1);
  return (
    <div className="chart">
      {rows.map((row, i) => (
        <div className="chart-row" key={i}>
          <div className="chart-label" title={String(row[0])}>
            {String(row[0])}
          </div>
          <div className="chart-track">
            <div
              className={`chart-bar${row[valueIndex] < 0 ? ' negative' : ''}`}
              style={{ width: `${(Math.abs(row[valueIndex]) / max) * 100}%` }}
            />
          </div>
          <div className="chart-value">{formatCell(row[valueIndex])}</div>
        </div>
      ))}
      <div className="chart-caption">
        {columns[valueIndex]} by {columns[0]}
      </div>
    </div>
  );
}

function ResultsTable({ columns, rows }) {
  if (columns.length === 0) return <p className="explanation">No rows returned.</p>;
  return (
    <div className="table-wrap">
      <table>
        <thead>
          <tr>
            {columns.map((c) => (
              <th key={c}>{c}</th>
            ))}
          </tr>
        </thead>
        <tbody>
          {rows.slice(0, 200).map((row, i) => (
            <tr key={i}>
              {row.map((cell, j) => (
                <td key={j}>{formatCell(cell)}</td>
              ))}
            </tr>
          ))}
        </tbody>
      </table>
    </div>
  );
}

function formatCell(value) {
  if (typeof value === 'number' && !Number.isInteger(value)) {
    return value.toLocaleString('en-US', { maximumFractionDigits: 2 });
  }
  if (typeof value === 'number' && Math.abs(value) >= 1000) {
    return value.toLocaleString('en-US');
  }
  return value ?? '—';
}
